--[[
脚本名字: RemoteNames
脚本文件: RemoteNames.lua
脚本类型: ModuleScript
Studio放置路径: ReplicatedStorage/Shared/RemoteNames
]]

local RemoteNames = {
    RootFolder = "Events",
    SystemEventsFolder = "SystemEvents",
    BattleEventsFolder = "BattleEvents",
    System = {
        PlayerStateSync = "PlayerStateSync",
        RequestPlayerStateSync = "RequestPlayerStateSync",
        RequestAttributeUpgrade = "RequestAttributeUpgrade",
        AttributeUpgradeFeedback = "AttributeUpgradeFeedback",
        RequestAttributeCapUpgrade = "RequestAttributeCapUpgrade",
        AttributeCapUpgradeFeedback = "AttributeCapUpgradeFeedback",
        ArenaTransitionFeedback = "ArenaTransitionFeedback",
        DeathFeedback = "DeathFeedback",
        KillInfoFeedback = "KillInfoFeedback",
        StudioBotCommand = "StudioBotCommand",
        LevelUpFeedback = "LevelUpFeedback",
        PortalJoinPrompt = "PortalJoinPrompt",
        RequestJoinBattle = "RequestJoinBattle",
        RequestRebirth = "RequestRebirth",
        RebirthFeedback = "RebirthFeedback",
        RequestDefeatedAction = "RequestDefeatedAction",
        RequestPotionAction = "RequestPotionAction",
        PotionFeedback = "PotionFeedback",
        SpecialEventSync = "SpecialEventSync",
        RequestSpecialEventSync = "RequestSpecialEventSync",
        GroupRewardPrompt = "GroupRewardPrompt",
        RequestGroupReward = "RequestGroupReward",
        GroupRewardFeedback = "GroupRewardFeedback",
        PromptGroupJoin = "PromptGroupJoin",
        PromptFavoritePlace = "PromptFavoritePlace",
        FavoritePlacePromptStarted = "FavoritePlacePromptStarted",
        FavoritePlacePromptResult = "FavoritePlacePromptResult",
        PromptActivityRsvp = "PromptActivityRsvp",
        ActivityRsvpPromptStarted = "ActivityRsvpPromptStarted",
        ActivityRsvpPromptResult = "ActivityRsvpPromptResult",
        WeaponUnlockPrompt = "WeaponUnlockPrompt",
        RequestWeaponUnlockReward = "RequestWeaponUnlockReward",
        WeaponUnlockRewardFeedback = "WeaponUnlockRewardFeedback",
        RequestWheelStateSync = "RequestWheelStateSync",
        WheelStateSync = "WheelStateSync",
        RequestWheelSpin = "RequestWheelSpin",
        WheelSpinResult = "WheelSpinResult",
        RequestSkinStateSync = "RequestSkinStateSync",
        SkinStateSync = "SkinStateSync",
        RequestSkinPurchase = "RequestSkinPurchase",
        RequestSkinEquip = "RequestSkinEquip",
        SkinFeedback = "SkinFeedback",
        RequestSubscriptionStateSync = "RequestSubscriptionStateSync",
        SubscriptionStateSync = "SubscriptionStateSync",
        RequestSubscriptionClaim = "RequestSubscriptionClaim",
        SubscriptionFeedback = "SubscriptionFeedback",
        RequestShopStateSync = "RequestShopStateSync",
        ShopStateSync = "ShopStateSync",
        RequestShopStarterPackClaim = "RequestShopStarterPackClaim",
        RequestShopPurchaseContext = "RequestShopPurchaseContext",
        ShopRewardFeedback = "ShopRewardFeedback",
        RequestCodeRedeem = "RequestCodeRedeem",
        CodeRedeemFeedback = "CodeRedeemFeedback",
        OnlineRewardStateSync = "OnlineRewardStateSync",
        RequestOnlineRewardStateSync = "RequestOnlineRewardStateSync",
        RequestOnlineRewardClaim = "RequestOnlineRewardClaim",
        SevenDayLoginRewardStateSync = "SevenDayLoginRewardStateSync",
        RequestSevenDayLoginRewardStateSync = "RequestSevenDayLoginRewardStateSync",
        RequestSevenDayLoginRewardClaim = "RequestSevenDayLoginRewardClaim",
        RequestOptionStateSync = "RequestOptionStateSync",
        RequestOptionUpdate = "RequestOptionUpdate",
        RequestFriendsRankingStateSync = "RequestFriendsRankingStateSync",
        FriendsRankingStateSync = "FriendsRankingStateSync",
        TaskStateSync = "TaskStateSync",
        RequestTaskStateSync = "RequestTaskStateSync",
        RequestTaskClaim = "RequestTaskClaim",
        RequestInviteTaskProgress = "RequestInviteTaskProgress",
        ChestStateSync = "ChestStateSync",
        RequestChestStateSync = "RequestChestStateSync",
        RequestChestOpen = "RequestChestOpen",
        RequestChestRewardClaim = "RequestChestRewardClaim",
    },
    Battle = {
        PickupFeedback = "PickupFeedback",
        ExperienceFeedback = "ExperienceFeedback",
        LocalMonsterSpawnToken = "LocalMonsterSpawnToken",
        LocalMonsterKilled = "LocalMonsterKilled",
        LocalMonsterHitPlayer = "LocalMonsterHitPlayer",
        WeaponStateSync = "WeaponStateSync",
        CombatFeedback = "CombatFeedback",
        BuffFeedback = "BuffFeedback",
        BossFeedback = "BossFeedback",
        BossHitFeedback = "BossHitFeedback",
        LeaderboardSync = "LeaderboardSync",
        ArenaProgressSync = "ArenaProgressSync",
        NukeCinematic = "NukeCinematic",
        RevengeCinematic = "RevengeCinematic",
        NukeLocalMonsterSweep = "NukeLocalMonsterSweep",
    },
}

return RemoteNames
